services:
  - type: web
    name: rasa-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: RASA_API_KEY
        value: "your_rasa_api_key"  # Use your actual Rasa API key here
