# render.yaml
version: 1
services:
  - type: web
    name: flask-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here  # Set this directly in Render's dashboard instead
